#!/usr/bin/env bash
set -eu
chooser=""
cwd=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --chooser-file) chooser=$2; shift 2 ;;
    --cwd-file) cwd=$2; shift 2 ;;
    *) shift ;;
  esac
done
selection=${FAKE_ELIO_SELECTION:-}
if [ -n "${FAKE_ELIO_SELECTION_ONCE:-}" ] && [ -e "$FAKE_ELIO_SELECTION_ONCE" ]; then
  selection=""
elif [ -n "${FAKE_ELIO_SELECTION_ONCE:-}" ]; then
  : > "$FAKE_ELIO_SELECTION_ONCE"
fi
printf '%s\n' "$selection" > "$chooser"
printf '%s' "${FAKE_ELIO_CWD:-}" > "$cwd"
exit "${FAKE_ELIO_EXIT:-0}"
